server:
  port: 10000
  servlet:
    session.timeout: 60000
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://182.92.151.98:3306/school?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


